### ISSUE TITLE
Merge packages

### ISSUE THREAD

**Issue by zimme** [jamgold/isdevelopment#1]
How about you and @jboulhous talk things over and "merge" packages and keep the best implementation and `meteor admin set-unmigrated <package:name>` for the "losing" package?

This is a pretty basic functionality and think it's better if there's one package instead of two,
makes it easier to find and such. :smile:

Just close this issue if you feel it's unnecessary

**Comment by jamgold** [comment]
@zimme did you post the same on @jboulhouse git issues?

**Comment by zimme** [comment]
No but I mentioned him so I believe he should be getting the message too?

**Comment by jboulhous** [comment]
Hi,
The two packages uses a differents techniques and provide 'different' information to app code, @zimme should take a look at both packages code.

**Comment by zimme** [comment]
I've looked at the code. Both packages set Meteor.isDevelopment to `true` if in development mode, sure it's done using different techniques, but the result is the same.

In this package you get either `true` or `false`, and in the other package you get `true` or `undefined`.

This, however, was just a suggestion and if you guys feel that there's no need to combine your efforts, no harm done.

**Comment by zimme** [comment]
Should I close this?

**Comment by jamgold** [comment]
I guess. I am happy to unmigrate my package if it is confusing

**Comment by zimme** [comment]
I'll close this then.

I have no major problems with there being two packages which essentially does the same thing. I just felt it was somewhat unnecessary, hence this issue.

If you wanna keep your package, feel free to do so.

I just thought that you guys, together, might be able to promote one package with more ease than two packages.

I feel it's worth trying to work together as much as possible, and if opinions or needs diverge, then branch out based on that.

P.S.
This is a very useful thing to have and I'm grateful that you guys took the time to give us (the community) a package for it.
