### ISSUE TITLE
Not working right on Meteor 1.2.1

### ISSUE THREAD

**Issue by bySabi** [jamgold/isdevelopment#2]
Hi @jamgold this packages is not working right on Meteor 1.2.1, not tested on old versions.
when `__meteor_runtime_config__.isDevelopment` is set I can see it on client console. But on server side `__meteor_runtime_config__.isDevelopment` is never set.
This package is still active??

**Comment by bySabi** [comment]
I remplace this:

```
    Meteor.startup(function () {
        // code to run on server at startup
        __meteor_runtime_config__.isDevelopment = process.env.NODE_ENV == 'development';
    });
```

for this: 

```
Meteor.isDevelopment = __meteor_runtime_config__.isDevelopment = process.env.NODE_ENV == 'development';
```

**Comment by jamgold** [comment]
Still works, even on 1.2.1. Just tested. I did update the version to 0.0.2 and added some minor code

**Comment by bySabi** [comment]
Nice! now is work here. 
Thanks.
